version: "3.8"

services:
  mysql-service:
    image: custom-mysql-swarm:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
    driver: overlay
